services:
    grafana:
        extends:
            file: docker-compose.base.yml
            service: grafana
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - nginx
    wait-for-api:
        extends:
            file: docker-compose.base.yml
            service: wait-for-api
        depends_on:
            nginx:
                condition: service_healthy
    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        depends_on:
            - api

    api:
        extends:
            file: docker-compose.base.yml
            service: api
        depends_on:
            redis:
                condition: service_healthy
            db:
                condition: service_healthy
            minio:
                condition: service_healthy

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis
        volumes:
            - redis_data:/data

    db:
        extends:
            file: docker-compose.base.yml
            service: db
        volumes:
            - pg_data:/var/lib/postgresql/data/

    minio:
        extends:
            file: docker-compose.base.yml
            service: minio
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"

    nginx-s3-gateway:
        extends:
            file: docker-compose.base.yml
            service: nginx-s3-gateway
        depends_on:
            minio:
                condition: service_healthy

volumes:
    pg_data:
    redis_data:
    minio_data:
    grafana_data:
