"""['image path']

Revision ID: 104d879aa6e2
Revises: 0d266f01ec6b
Create Date: 2025-02-17 07:50:38.887951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104d879aa6e2'
down_revision = '0d266f01ec6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('image_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'image_path')
    # ### end Alembic commands ###