"""['click']

Revision ID: 37db1ceaba05
Revises: 5d9b588f7485
Create Date: 2025-02-14 15:56:38.492734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37db1ceaba05'
down_revision = '5d9b588f7485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('click_id', sa.UUID(), nullable=False),
    sa.Column('ad_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('cost_per_click', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('click_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    # ### end Alembic commands ###