"""['add is_deleted']

Revision ID: 58613a4cf088
Revises: 104d879aa6e2
Create Date: 2025-02-18 15:03:29.312260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58613a4cf088'
down_revision = '104d879aa6e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'is_deleted')
    # ### end Alembic commands ###