"""['campaign']

Revision ID: 5d9b588f7485
Revises: 7e59e1e1764f
Create Date: 2025-02-13 16:35:07.400554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9b588f7485'
down_revision = '7e59e1e1764f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.Column('impressions_limit', sa.Integer(), nullable=False),
    sa.Column('clicks_limit', sa.Integer(), nullable=False),
    sa.Column('cost_per_impression', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_click', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ad_title', sa.Text(), nullable=False),
    sa.Column('ad_text', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('age_from', sa.Integer(), nullable=True),
    sa.Column('age_to', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'ALL', name='targetgender'), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.advertiser_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign')
    # ### end Alembic commands ###