"""['click day']

Revision ID: 616e892f436d
Revises: 37db1ceaba05
Create Date: 2025-02-14 16:01:02.132829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616e892f436d'
down_revision = '37db1ceaba05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'day')
    # ### end Alembic commands ###