"""['change field names']

Revision ID: 6464071ffffe
Revises: 
Create Date: 2025-02-12 20:48:12.084690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6464071ffffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertiser',
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.CheckConstraint('LENGTH(name) BETWEEN 2 AND 200'),
    sa.PrimaryKeyConstraint('advertiser_id')
    )
    op.create_table('client',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.CheckConstraint('LENGTH(location) BETWEEN 2 AND 200'),
    sa.CheckConstraint('LENGTH(login) BETWEEN 2 AND 80'),
    sa.CheckConstraint('age BETWEEN 0 AND 100'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('relevance',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.advertiser_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('client_id', 'advertiser_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relevance')
    op.drop_table('client')
    op.drop_table('advertiser')
    # ### end Alembic commands ###