"""['indexes']

Revision ID: c7c730a97a19
Revises: 58613a4cf088
Create Date: 2025-02-18 19:00:22.087496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c730a97a19'
down_revision = '58613a4cf088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaign_advertiser_id'), 'campaign', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_campaign_age_from'), 'campaign', ['age_from'], unique=False)
    op.create_index(op.f('ix_campaign_age_to'), 'campaign', ['age_to'], unique=False)
    op.create_index(op.f('ix_campaign_gender'), 'campaign', ['gender'], unique=False)
    op.create_index(op.f('ix_campaign_is_deleted'), 'campaign', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_campaign_location'), 'campaign', ['location'], unique=False)
    op.create_index(op.f('ix_click_ad_id'), 'click', ['ad_id'], unique=False)
    op.create_index(op.f('ix_click_client_id'), 'click', ['client_id'], unique=False)
    op.create_index(op.f('ix_click_cost_per_click'), 'click', ['cost_per_click'], unique=False)
    op.create_unique_constraint(None, 'click', ['client_id', 'ad_id'])
    op.create_index(op.f('ix_impression_ad_id'), 'impression', ['ad_id'], unique=False)
    op.create_index(op.f('ix_impression_client_id'), 'impression', ['client_id'], unique=False)
    op.create_index(op.f('ix_impression_cost_per_impression'), 'impression', ['cost_per_impression'], unique=False)
    op.create_unique_constraint(None, 'impression', ['client_id', 'ad_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'impression', type_='unique')  # type: ignore
    op.drop_index(op.f('ix_impression_cost_per_impression'), table_name='impression')
    op.drop_index(op.f('ix_impression_client_id'), table_name='impression')
    op.drop_index(op.f('ix_impression_ad_id'), table_name='impression')
    op.drop_constraint(None, 'click', type_='unique')  # type: ignore
    op.drop_index(op.f('ix_click_cost_per_click'), table_name='click')
    op.drop_index(op.f('ix_click_client_id'), table_name='click')
    op.drop_index(op.f('ix_click_ad_id'), table_name='click')
    op.drop_index(op.f('ix_campaign_location'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_is_deleted'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_gender'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_age_to'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_age_from'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_advertiser_id'), table_name='campaign')
    # ### end Alembic commands ###