{
 "title": "Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Просмотры и клики по дням",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH \ndaily_impressions AS (\n    SELECT \n        day,\n        COUNT(impression_id) AS impressions_count\n    FROM impression\n    GROUP BY day\n),\ndaily_clicks AS (\n    SELECT \n        day,\n        COUNT(click_id) AS clicks_count\n    FROM click\n    GROUP BY day\n)\nSELECT\n    COALESCE(i.day, c.day) AS day,\n    COALESCE(i.impressions_count, 0) AS impressions_count,\n    COALESCE(c.clicks_count, 0) AS clicks_count\nFROM daily_impressions i\nFULL JOIN daily_clicks c ON i.day = c.day\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Просмотры по дням",
   "type": "trend",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    day AS \"day\",\n    COUNT(impression_id) as \"count\"\nFROM \n    impression\nGROUP BY \n    day\nORDER BY \n    day;"
    }
   ]
  },
  {
   "title": "Соотношение рекламодателей к клиентам",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Общая статистика",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Соотношение кликов и просмотров",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  {
   "title": "Прибыль по дням",
   "type": "trend",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH \nimpressions_profit AS (\n    SELECT \n        day,\n        SUM(cost_per_impression) AS total_impressions\n    FROM impression\n    GROUP BY day\n),\nclicks_profit AS (\n    SELECT \n        day,\n        SUM(cost_per_click) AS total_clicks\n    FROM click\n    GROUP BY day\n)\nSELECT\n    COALESCE(i.day, c.day) AS day,\n    COALESCE(i.total_impressions, 0) AS impressions_profit,\n    COALESCE(c.total_clicks, 0) AS clicks_profit,\n    COALESCE(i.total_impressions, 0) + COALESCE(c.total_clicks, 0) AS total_profit\nFROM impressions_profit i\nFULL JOIN clicks_profit c ON i.day = c.day\nORDER BY day;"
    }
   ]
  }
 ]
}